# 05

On Java 第十五章的阅读笔记，主要内容是异常

异常是用于处理运行时产生的错误的机制

## 异常

异常机制使得正常执行的代码和用于处理错误的代码分离，使得程序的编写和调试更加有条理

异常是阻止当前方法继续执行的问题，区分于能在当前环境解决的普通问题，发生异常时当前信息不足以解决问题，所以需要将问题提交给更高级的环境，即抛出异常

抛出异常后正常的控制流被终止，异常处理机制接管程序并决定之后的运行情况。抛出异常采用 `throw` 关键字

```java
if(t == null)
    throw new NullPointerException();
```

标准的异常都有两个构造器，一个无参构造器，一个构造器接受一个字符串作为参数，提供额外的异常相关的信息

## 异常捕获

监控区域（guarded region）是一段可能会产生异常的代码，在其后跟随着处理异常的代码

`try` 关键字后跟着一个程序块，其中的语句可能会产生异常，如果异常产生了就会被捕捉，之后的处理就发生在 `catch` 块中

```java
try {
    // Code that might generate exceptions
} catch(Type1 id1) {
    // Handle exceptions of Type1
} catch(Type2 id2) {
    // Handle exceptions of Type2
} catch(Type3 id3) {
    // Handle exceptions of Type3
}
```

异常处理程序必须紧跟在 `try` 之后，抛出的异常按顺序与每个 `catch` 捕获的异常匹配，一旦匹配成功则后续的匹配不再进行，只有被匹配的 `catch` 子句才会进行，基类的处理程序可以捕获派生类的异常对象

如果 `catch` 捕获 `Exception` 类，则所有异常都会被捕获，如果需要这种行为，将该 `catch` 子句放在末尾，以避免之前的更具体的捕获语句永远不会被执行。如果想捕获多个异常并且在一个子句中处理，则将不同异常用 `|` 连接起来。如果当前环境处理不了异常，则可以在 `catch` 子句中将异常再次抛出，交给更高级的环境处理，如果想要保存重新抛出点的栈信息，使用 `fillInStackTrace`  方法，这个方法返回一个填充了当前栈信息的异常对象

```java
public class MultiCatch {
    void x() throws Except1, Except2, Except3, Except4 {}
    void process() {}
    void f() {
        try {
            x();
        } catch(Except1 | Except2 | Except3 | Except4 e) {
            process();
        }
    }
}
```

可以使用 `getStackTrace` 获取栈帧信息，这个方法将返回一个由栈轨迹中的元素所构成的数组，其中每一个元素都表示栈中的一桢

如果想要捕获一个异常后抛出一个新异常，并且想保存原异常的信息，可以将原异常传入新异常的构造器，根据异常链即可追踪到最初抛出异常的位置，但是只有 `Error/Exception/RuntimeException` 有此构造器，其他异常则使用 `initCause` 方法

Java 的异常处理模型是终止模型，即异常发生后方法不会再回来进行，如果希望能在修正错误后继续进行，则或者不抛出异常而是采用别的方法修正错误，或是循环调用 `try` 子句直至成功执行

## 自定义异常

Java 提供的异常类型不可能涵盖所有的异常类型，故可以根据需要自行定义异常，一般常用的方法是继承自已有的异常类型

```java
class SimpleException extends Exception {}
```

一般对异常来说最重要的信息就是异常名，所以有没有带字符串的构造器并不是非常重要，处理程序一般也不期望能得到额外的信息

## 异常声明

Java 强制异常的抛出者告知方法使用者可能会抛出的异常，即异常声明。异常声明是方法声明的一部分，一般在参数列表之后，使用 `throws` 关键字定义

```java
void f() throws TooBig, TooSmall, DivZero { // ...
```

不声明异常的方法默认不会抛出异常（除了 `RuntimeException`），但是声明了异常的方法可以不抛出异常，如在抽象类或是接口定义的方法

## Java 标准异常

Java 所有可抛出的类都有一个基类 `Throwable`，从中继承了两个类

* `Error` 表示编译时错误和系统错误，这部分异常不需要程序员处理
* `Exception` 是可抛出异常的基本类型，一般程序员需要处理的也是这一部分

一个异常代表的具体情况一般可以从其类名和继承自的父类看出

`RuntimeException` 是一个特例，代表运行时错误，Java 自动将其抛出而不需要显式在异常声明中写出，抛出 `RuntimeException` 表示发生了编程错误，如

* 无法预料的错误，如传进来的参数是 null
* 应该在代码中检查的错误，如数组下标越界

如果不捕获运行时错误，则其会一路传播到 main 并最终导致程序终止

只有 `Error` 和 `RuntimeException` 可以被忽略，其他被抛出的异常都由编译器保证一定要得到处理

## Finally

如果有无论异常是否发生都要执行的语句，则可以使用 `finally` 子句

```java
try {
// The guarded region: Dangerous activities
// that might throw A, B, or C
} catch(A a1) {
// Handler for situation A
} catch(B b1) {
// Handler for situation B
} catch(C c1) {
// Handler for situation C
} finally {
// Activities that happen every time
}
```

其中的代码总能运行。

`finally` 子句用于执行清理工作，如关闭被打开的文件/网络连接等

即使在 `try` 中返回，`finally` 也会执行

在构造器中使用 `finally` 需要格外小心，一般推荐的解决方案是使用嵌套的 `try-catch`

## 异常限制

当重写方法时，新方法只能抛出在原方法的异常声明里列出的方法，这是为了确保出现基类的地方都可以用派生类代替

派生方法可以不抛出异常，但是不能抛出额外的异常

不能基于异常说明重载方法

## Try-With-Resources

可以在 `try` 后跟一个括号，其中的内容称为资源规范头（resource specification header），在其中打开的对象在 `try` 结束后会自动关闭，其必须实现 `java.lang.AutoCloseable` 接口

```java
import java.io.*;
public class TryWithResources {
    public static void main(String[] args) {
        try(
                InputStream in = new FileInputStream(
                        new File("TryWithResources.java"))
        ) {
            int contents = in.read();
            // Process contents
        } catch(IOException e) {
            // Handle the error
        }
    }
}
```

资源规范头可以有多个定义，每个定义用分号分开

